server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgres.sql.drive

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/liquibase/db.changelog.yml
    enabled: true